-- AUTO-GENERATED by scripts/gen-supabase-seed.mjs from src/data/mock/seed.ts.
-- One-time import so the app runs on real Supabase infra. Re-run to refresh.
-- News + Resources are authored here (Supabase-native). Businesses come from the
-- mock import now; later they sync from GoHighLevel (businesses.ghl_id).
-- Runs as the postgres role on `supabase db reset` (bypasses RLS; triggers still fire).

truncate table public.recommendations, public.bulletins, public.events,
  public.news_articles, public.resources, public.businesses restart identity cascade;

-- businesses
insert into public.businesses
  (id, name, slug, category, subcategories, description, address, lat, lng, phone, website, email, hours, photos, amenity_tags, claimed, verified, tier, created_at, recommend_count)
values ('b_juniper', 'Juniper & Sage Cafe', 'juniper-and-sage-cafe', 'Cafe', ARRAY['Breakfast','Coffee']::text[], 'Neighborhood cafe serving coffee, breakfast & fresh-baked goods. Dog-friendly patio.', '512 SW Evergreen Ave, Redmond, OR', 44.2726, -121.1739, '(541) 555-0142', 'https://example.com/juniper', null, '{"week":{"mon":{"open":"","close":"","closed":true},"tue":{"open":"07:00","close":"18:00"},"wed":{"open":"07:00","close":"18:00"},"thu":{"open":"07:00","close":"18:00"},"fri":{"open":"07:00","close":"18:00"},"sat":{"open":"08:00","close":"15:00"},"sun":{"open":"08:00","close":"15:00"}}}'::jsonb, ARRAY['/mock/juniper-1.jpg']::text[], ARRAY['Outdoor seating','Kid-friendly','Wi-Fi','Dog-friendly']::text[], true, true, 'free', '2024-03-01'::timestamptz, 43);
insert into public.businesses
  (id, name, slug, category, subcategories, description, address, lat, lng, phone, website, email, hours, photos, amenity_tags, claimed, verified, tier, created_at, recommend_count)
values ('b_basalt', 'Basalt Coffee Roasters', 'basalt-coffee-roasters', 'Coffee', ARRAY['Roastery']::text[], 'Small-batch roaster and tasting bar in the heart of downtown.', '210 SW 6th St, Redmond, OR', 44.2741, -121.1722, '(541) 555-0119', null, null, '{"week":{"mon":{"open":"06:30","close":"17:00"},"tue":{"open":"06:30","close":"17:00"},"wed":{"open":"06:30","close":"17:00"},"thu":{"open":"06:30","close":"17:00"},"fri":{"open":"06:30","close":"17:00"},"sat":{"open":"07:00","close":"16:00"},"sun":{"open":"07:00","close":"14:00"}}}'::jsonb, ARRAY['/mock/basalt-1.jpg']::text[], ARRAY['Wi-Fi','Outdoor seating','Takeout']::text[], true, true, 'free', '2024-05-10'::timestamptz, 67);
insert into public.businesses
  (id, name, slug, category, subcategories, description, address, lat, lng, phone, website, email, hours, photos, amenity_tags, claimed, verified, tier, created_at, recommend_count)
values ('b_cascade', 'Cascade Hardware', 'cascade-hardware', 'Hardware', ARRAY['Home','Garden']::text[], 'Locally owned hardware store — tools, paint, garden, and friendly advice.', '1024 NW Cedar Ave, Redmond, OR', 44.2789, -121.1765, '(541) 555-0188', null, null, '{"week":{"mon":{"open":"07:30","close":"19:00"},"tue":{"open":"07:30","close":"19:00"},"wed":{"open":"07:30","close":"19:00"},"thu":{"open":"07:30","close":"19:00"},"fri":{"open":"07:30","close":"19:00"},"sat":{"open":"08:00","close":"18:00"},"sun":{"open":"09:00","close":"16:00"}}}'::jsonb, '{}', ARRAY['Parking','Wheelchair accessible']::text[], true, false, 'free', '2023-11-20'::timestamptz, 29);
insert into public.businesses
  (id, name, slug, category, subcategories, description, address, lat, lng, phone, website, email, hours, photos, amenity_tags, claimed, verified, tier, created_at, recommend_count)
values ('b_highdesert', 'High Desert Bakery', 'high-desert-bakery', 'Bakery', ARRAY['Cafe']::text[], 'Sourdough, pastries, and seasonal pies baked fresh daily.', '78 SW Deschutes Ave, Redmond, OR', 44.271, -121.1751, '(541) 555-0173', null, null, '{"week":{"mon":{"open":"","close":"","closed":true},"tue":{"open":"07:00","close":"16:00"},"wed":{"open":"07:00","close":"16:00"},"thu":{"open":"07:00","close":"16:00"},"fri":{"open":"07:00","close":"16:00"},"sat":{"open":"07:00","close":"14:00"},"sun":{"open":"08:00","close":"13:00"}}}'::jsonb, ARRAY['/mock/bakery-1.jpg']::text[], ARRAY['Gluten-free','Kid-friendly','Vegan options']::text[], true, true, 'free', '2024-01-15'::timestamptz, 31);
insert into public.businesses
  (id, name, slug, category, subcategories, description, address, lat, lng, phone, website, email, hours, photos, amenity_tags, claimed, verified, tier, created_at, recommend_count)
values ('b_dailygrind', 'The Daily Grind', 'the-daily-grind', 'Cafe', ARRAY['Bakery','Coffee']::text[], 'Cozy corner cafe with espresso, scones, and a quiet back room for working.', '335 SW Forest Ave, Redmond, OR', 44.2698, -121.1718, '(541) 555-0204', null, null, '{"week":{"mon":{"open":"06:00","close":"19:00"},"tue":{"open":"06:00","close":"19:00"},"wed":{"open":"06:00","close":"19:00"},"thu":{"open":"06:00","close":"19:00"},"fri":{"open":"06:00","close":"20:00"},"sat":{"open":"07:00","close":"20:00"},"sun":{"open":"07:00","close":"17:00"}}}'::jsonb, '{}', ARRAY['Wi-Fi','Outdoor seating','Vegan options']::text[], true, false, 'free', '2025-02-02'::timestamptz, 22);
insert into public.businesses
  (id, name, slug, category, subcategories, description, address, lat, lng, phone, website, email, hours, photos, amenity_tags, claimed, verified, tier, created_at, recommend_count)
values ('b_smithrock', 'Smith Rock Outfitters', 'smith-rock-outfitters', 'Outdoors', ARRAY['Recreation','Retail']::text[], 'Climbing, hiking & camping gear — rentals, guides, and trail beta from locals.', '640 NW 5th St, Redmond, OR', 44.2767, -121.1744, '(541) 555-0231', 'https://example.com/smithrock', null, '{"week":{"mon":{"open":"09:00","close":"18:00"},"tue":{"open":"09:00","close":"18:00"},"wed":{"open":"09:00","close":"18:00"},"thu":{"open":"09:00","close":"18:00"},"fri":{"open":"09:00","close":"19:00"},"sat":{"open":"08:00","close":"19:00"},"sun":{"open":"08:00","close":"17:00"}}}'::jsonb, ARRAY['/mock/smithrock-1.jpg']::text[], ARRAY['Parking','Wheelchair accessible','Dog-friendly']::text[], true, true, 'free', '2023-08-12'::timestamptz, 58);
insert into public.businesses
  (id, name, slug, category, subcategories, description, address, lat, lng, phone, website, email, hours, photos, amenity_tags, claimed, verified, tier, created_at, recommend_count)
values ('b_riverbend', 'Riverbend Family Dental', 'riverbend-family-dental', 'Health', ARRAY['Medical','Wellness']::text[], 'Gentle, modern family dentistry. New patients welcome.', '1450 NW Canal Blvd, Redmond, OR', 44.2831, -121.1802, '(541) 555-0266', 'https://example.com/riverbend', null, '{"week":{"mon":{"open":"08:00","close":"17:00"},"tue":{"open":"08:00","close":"17:00"},"wed":{"open":"08:00","close":"17:00"},"thu":{"open":"08:00","close":"17:00"},"fri":{"open":"08:00","close":"14:00"},"sat":{"open":"","close":"","closed":true},"sun":{"open":"","close":"","closed":true}}}'::jsonb, '{}', ARRAY['Parking','Wheelchair accessible']::text[], true, true, 'free', '2022-06-01'::timestamptz, 37);
insert into public.businesses
  (id, name, slug, category, subcategories, description, address, lat, lng, phone, website, email, hours, photos, amenity_tags, claimed, verified, tier, created_at, recommend_count)
values ('b_mountainview', 'Mountain View Auto Repair', 'mountain-view-auto-repair', 'Auto', ARRAY['Repair']::text[], 'Honest, full-service auto repair and maintenance. ASE-certified techs.', '2210 S Hwy 97, Redmond, OR', 44.2562, -121.169, '(541) 555-0299', null, null, '{"week":{"mon":{"open":"07:30","close":"17:30"},"tue":{"open":"07:30","close":"17:30"},"wed":{"open":"07:30","close":"17:30"},"thu":{"open":"07:30","close":"17:30"},"fri":{"open":"07:30","close":"17:00"},"sat":{"open":"","close":"","closed":true},"sun":{"open":"","close":"","closed":true}}}'::jsonb, '{}', ARRAY['Parking','Wheelchair accessible']::text[], false, false, 'free', '2024-09-18'::timestamptz, 14);
insert into public.businesses
  (id, name, slug, category, subcategories, description, address, lat, lng, phone, website, email, hours, photos, amenity_tags, claimed, verified, tier, created_at, recommend_count)
values ('b_threesisters', 'Three Sisters Provisions', 'three-sisters-provisions', 'Grocery', ARRAY['Retail']::text[], 'Independent grocer with local produce, bulk goods, and regional makers.', '418 SW Glacier Ave, Redmond, OR', 44.2705, -121.1772, '(541) 555-0312', null, null, '{"week":{"mon":{"open":"08:00","close":"20:00"},"tue":{"open":"08:00","close":"20:00"},"wed":{"open":"08:00","close":"20:00"},"thu":{"open":"08:00","close":"20:00"},"fri":{"open":"08:00","close":"21:00"},"sat":{"open":"08:00","close":"21:00"},"sun":{"open":"09:00","close":"19:00"}}}'::jsonb, ARRAY['/mock/provisions-1.jpg']::text[], ARRAY['Parking','Vegan options','Gluten-free','Wheelchair accessible']::text[], true, true, 'free', '2023-04-22'::timestamptz, 49);
insert into public.businesses
  (id, name, slug, category, subcategories, description, address, lat, lng, phone, website, email, hours, photos, amenity_tags, claimed, verified, tier, created_at, recommend_count)
values ('b_canyon', 'Canyon Bloom Florist', 'canyon-bloom-florist', 'Retail', ARRAY['Boutique']::text[], 'Seasonal arrangements and house plants, designed in-shop. Same-day delivery.', '127 SW 7th St, Redmond, OR', 44.2733, -121.1709, '(541) 555-0345', 'https://example.com/canyonbloom', null, '{"week":{"mon":{"open":"09:00","close":"17:00"},"tue":{"open":"09:00","close":"17:00"},"wed":{"open":"09:00","close":"17:00"},"thu":{"open":"09:00","close":"17:00"},"fri":{"open":"09:00","close":"18:00"},"sat":{"open":"10:00","close":"16:00"},"sun":{"open":"","close":"","closed":true}}}'::jsonb, ARRAY['/mock/florist-1.jpg']::text[], ARRAY['Wheelchair accessible','Takeout']::text[], true, false, 'free', '2025-05-01'::timestamptz, 8);

-- bulletins
insert into public.bulletins (id, business_id, body, image, link_cta, scheduled_for, status, created_at)
values ('bl_1', 'b_juniper', 'Fresh sourdough — Saturdays only, while it lasts.', null, null, null, 'live', '2026-06-25T08:00:00'::timestamptz);
insert into public.bulletins (id, business_id, body, image, link_cta, scheduled_for, status, created_at)
values ('bl_2', 'b_basalt', 'New fall roast just dropped. Come try a free pour-over sample.', null, null, null, 'live', '2026-06-23T09:30:00'::timestamptz);
insert into public.bulletins (id, business_id, body, image, link_cta, scheduled_for, status, created_at)
values ('bl_3', 'b_highdesert', 'Strawberry-rhubarb pies are back this weekend. Pre-order by Friday.', null, null, null, 'live', '2026-06-24T10:00:00'::timestamptz);
insert into public.bulletins (id, business_id, body, image, link_cta, scheduled_for, status, created_at)
values ('bl_4', 'b_smithrock', 'Free climbing-shoe demo day Saturday 10–2. All skill levels welcome.', null, null, null, 'live', '2026-06-22T12:00:00'::timestamptz);
insert into public.bulletins (id, business_id, body, image, link_cta, scheduled_for, status, created_at)
values ('bl_5', 'b_threesisters', 'Local cherries just arrived — first of the season.', null, null, null, 'live', '2026-06-26T07:30:00'::timestamptz);

-- events (start/end are Redmond wall-clock → America/Los_Angeles)
insert into public.events (id, business_id, title, description, start_at, end_at, venue_name, address, lat, lng, image, category, tags, status)
values ('e_1', 'b_juniper', 'Live acoustic night', 'An intimate evening of acoustic sets on the patio.', '2026-07-10 19:00:00 America/Los_Angeles'::timestamptz, null, 'Juniper & Sage Cafe', '512 SW Evergreen Ave, Redmond, OR', 44.2726, -121.1739, null, 'Music', '{}', 'upcoming');
insert into public.events (id, business_id, title, description, start_at, end_at, venue_name, address, lat, lng, image, category, tags, status)
values ('e_2', null, 'Saturday Farmers Market', 'Local growers, makers, and food carts every Saturday morning.', '2026-07-11 09:00:00 America/Los_Angeles'::timestamptz, null, 'Centennial Park', 'Centennial Park, Redmond, OR', 44.274, -121.173, null, 'Community', ARRAY['Free','Family']::text[], 'upcoming');
insert into public.events (id, business_id, title, description, start_at, end_at, venue_name, address, lat, lng, image, category, tags, status)
values ('e_3', null, 'Kids'' craft hour', 'Drop-in crafts for ages 4–10. Materials provided.', '2026-07-11 11:00:00 America/Los_Angeles'::timestamptz, null, 'Redmond Public Library', '827 SW Deschutes Ave, Redmond, OR', 44.27, -121.1758, null, 'Family', ARRAY['Free','Kids']::text[], 'upcoming');
insert into public.events (id, business_id, title, description, start_at, end_at, venue_name, address, lat, lng, image, category, tags, status)
values ('e_4', null, 'High Desert Brewfest', 'Regional breweries, live music, and food carts downtown.', '2026-07-17 16:00:00 America/Los_Angeles'::timestamptz, null, 'Downtown Redmond', 'SW 6th St, Redmond, OR', 44.2738, -121.1725, null, 'Festival', ARRAY['21+']::text[], 'upcoming');
insert into public.events (id, business_id, title, description, start_at, end_at, venue_name, address, lat, lng, image, category, tags, status)
values ('e_5', 'b_smithrock', 'Trail cleanup & potluck', 'Help tidy the river trail, then share a meal.', '2026-07-26 09:00:00 America/Los_Angeles'::timestamptz, null, 'Dry Canyon Trailhead', 'NW Quartz Ave, Redmond, OR', 44.281, -121.18, null, 'Outdoors', ARRAY['Free','Volunteer']::text[], 'upcoming');

-- news_articles
insert into public.news_articles (id, title, slug, excerpt, body, image, source, author, published_at)
values ('n_1', 'Downtown plaza project breaks ground', 'downtown-plaza-breaks-ground', 'Construction begins on the long-planned civic plaza this week.', 'Construction crews broke ground Monday on Redmond''s downtown civic plaza, a project years in the making. The plaza will add gathering space, public art, and a small stage for community events. City officials expect completion by next summer.', null, 'Redmond Spokesman', 'J. Ramirez', '2026-06-26T14:00:00'::timestamptz);
insert into public.news_articles (id, title, slug, excerpt, body, image, source, author, published_at)
values ('n_2', 'City council approves new bike lanes', 'council-approves-bike-lanes', 'Protected lanes are coming to two major corridors next year.', 'The Redmond City Council voted 5–2 Tuesday to fund protected bike lanes along Canal Boulevard and 6th Street, part of a broader active-transportation plan.', null, 'Central Oregon Daily', null, '2026-06-24T18:30:00'::timestamptz);
insert into public.news_articles (id, title, slug, excerpt, body, image, source, author, published_at)
values ('n_3', 'Summer concert series returns to the park', 'summer-concert-series-returns', 'Free Thursday-evening concerts run through August.', 'The beloved summer concert series is back at Sam Johnson Park, with free performances every Thursday evening through August. Bring a blanket.', null, 'Redmond Spokesman', null, '2026-06-20T09:00:00'::timestamptz);

-- resources
insert into public.resources (id, name, category, description, phone, url, address)
values ('r_1', 'Redmond Police (non-emergency)', 'emergency', 'Report & general inquiries', '(541) 555-0000', null, null);
insert into public.resources (id, name, category, description, phone, url, address)
values ('r_2', 'Redmond Fire & Rescue', 'emergency', 'Burn permits, safety info', '(541) 555-0011', null, null);
insert into public.resources (id, name, category, description, phone, url, address)
values ('r_3', 'City of Redmond', 'government', 'Permits, utilities, council', null, 'https://example.com/city', '411 SW 9th St, Redmond, OR');
insert into public.resources (id, name, category, description, phone, url, address)
values ('r_4', 'DMV — Redmond', 'government', 'Licenses & registration', null, 'https://example.com/dmv', '2410 SW 17th Pl, Redmond, OR');
insert into public.resources (id, name, category, description, phone, url, address)
values ('r_5', 'Redmond Public Library', 'community', 'Hours, programs, library cards', null, 'https://example.com/library', '827 SW Deschutes Ave, Redmond, OR');
insert into public.resources (id, name, category, description, phone, url, address)
values ('r_6', 'Pacific Power (outages)', 'utilities', 'Report outages & start/stop service', '(541) 555-0044', 'https://example.com/power', null);
